stages:
  - build
  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.8.6-jdk-11
  script:
    - mvn clean package

test:
    stage: test
    image: maven:3.8.6-jdk-11
    script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o '.*'
    coverage: "/Total.*?([0-9]{1,3})%/"


checkstyle:
    stage: checkstyle
    image: maven:3.8.6-jdk-11
    script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check

variables:
    DB_IP: localhost
    DB_PORT: 3306
    DB_USER: htoh
    DB_PASSWORD: htoh
    DB_DBNAME: ds_project_1
    

