// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package ro.tuc.ds2020.grpc;

public interface JoinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.ds2020.grpc.JoinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 error = 1;</code>
   * @return The error.
   */
  int getError();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
