// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package ro.tuc.ds2020.grpc;

public interface ReceiveMsgRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.ds2020.grpc.ReceiveMsgRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   * @return The user.
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   * @return The bytes for user.
   */
  com.google.protobuf.ByteString
      getUserBytes();
}
