// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package ro.tuc.ds2020.grpc;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.ds2020.grpc.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
