/**
 * @fileoverview gRPC-Web generated client stub for ro.tuc.ds2020.grpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.20.3
// source: greet.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.ro = {};
proto.ro.tuc = {};
proto.ro.tuc.ds2020 = {};
proto.ro.tuc.ds2020.grpc = require('./greet_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ro.tuc.ds2020.grpc.ChatServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ro.tuc.ds2020.grpc.ChatServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ro.tuc.ds2020.grpc.User,
 *   !proto.ro.tuc.ds2020.grpc.JoinResponse>}
 */
const methodDescriptor_ChatService_join = new grpc.web.MethodDescriptor(
  '/ro.tuc.ds2020.grpc.ChatService/join',
  grpc.web.MethodType.UNARY,
  proto.ro.tuc.ds2020.grpc.User,
  proto.ro.tuc.ds2020.grpc.JoinResponse,
  /**
   * @param {!proto.ro.tuc.ds2020.grpc.User} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ro.tuc.ds2020.grpc.JoinResponse.deserializeBinary
);


/**
 * @param {!proto.ro.tuc.ds2020.grpc.User} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ro.tuc.ds2020.grpc.JoinResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ro.tuc.ds2020.grpc.JoinResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ro.tuc.ds2020.grpc.ChatServiceClient.prototype.join =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ro.tuc.ds2020.grpc.ChatService/join',
      request,
      metadata || {},
      methodDescriptor_ChatService_join,
      callback);
};


/**
 * @param {!proto.ro.tuc.ds2020.grpc.User} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ro.tuc.ds2020.grpc.JoinResponse>}
 *     Promise that resolves to the response
 */
proto.ro.tuc.ds2020.grpc.ChatServicePromiseClient.prototype.join =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ro.tuc.ds2020.grpc.ChatService/join',
      request,
      metadata || {},
      methodDescriptor_ChatService_join);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ro.tuc.ds2020.grpc.ChatMessage,
 *   !proto.ro.tuc.ds2020.grpc.Empty>}
 */
const methodDescriptor_ChatService_sendMsg = new grpc.web.MethodDescriptor(
  '/ro.tuc.ds2020.grpc.ChatService/sendMsg',
  grpc.web.MethodType.UNARY,
  proto.ro.tuc.ds2020.grpc.ChatMessage,
  proto.ro.tuc.ds2020.grpc.Empty,
  /**
   * @param {!proto.ro.tuc.ds2020.grpc.ChatMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ro.tuc.ds2020.grpc.Empty.deserializeBinary
);


/**
 * @param {!proto.ro.tuc.ds2020.grpc.ChatMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ro.tuc.ds2020.grpc.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ro.tuc.ds2020.grpc.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ro.tuc.ds2020.grpc.ChatServiceClient.prototype.sendMsg =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ro.tuc.ds2020.grpc.ChatService/sendMsg',
      request,
      metadata || {},
      methodDescriptor_ChatService_sendMsg,
      callback);
};


/**
 * @param {!proto.ro.tuc.ds2020.grpc.ChatMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ro.tuc.ds2020.grpc.Empty>}
 *     Promise that resolves to the response
 */
proto.ro.tuc.ds2020.grpc.ChatServicePromiseClient.prototype.sendMsg =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ro.tuc.ds2020.grpc.ChatService/sendMsg',
      request,
      metadata || {},
      methodDescriptor_ChatService_sendMsg);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ro.tuc.ds2020.grpc.Empty,
 *   !proto.ro.tuc.ds2020.grpc.ChatMessage>}
 */
const methodDescriptor_ChatService_receiveMsg = new grpc.web.MethodDescriptor(
  '/ro.tuc.ds2020.grpc.ChatService/receiveMsg',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.ro.tuc.ds2020.grpc.Empty,
  proto.ro.tuc.ds2020.grpc.ChatMessage,
  /**
   * @param {!proto.ro.tuc.ds2020.grpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ro.tuc.ds2020.grpc.ChatMessage.deserializeBinary
);


/**
 * @param {!proto.ro.tuc.ds2020.grpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ro.tuc.ds2020.grpc.ChatMessage>}
 *     The XHR Node Readable Stream
 */
proto.ro.tuc.ds2020.grpc.ChatServiceClient.prototype.receiveMsg =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ro.tuc.ds2020.grpc.ChatService/receiveMsg',
      request,
      metadata || {},
      methodDescriptor_ChatService_receiveMsg);
};


/**
 * @param {!proto.ro.tuc.ds2020.grpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ro.tuc.ds2020.grpc.ChatMessage>}
 *     The XHR Node Readable Stream
 */
proto.ro.tuc.ds2020.grpc.ChatServicePromiseClient.prototype.receiveMsg =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ro.tuc.ds2020.grpc.ChatService/receiveMsg',
      request,
      metadata || {},
      methodDescriptor_ChatService_receiveMsg);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ro.tuc.ds2020.grpc.Empty,
 *   !proto.ro.tuc.ds2020.grpc.UserList>}
 */
const methodDescriptor_ChatService_getAllUsers = new grpc.web.MethodDescriptor(
  '/ro.tuc.ds2020.grpc.ChatService/getAllUsers',
  grpc.web.MethodType.UNARY,
  proto.ro.tuc.ds2020.grpc.Empty,
  proto.ro.tuc.ds2020.grpc.UserList,
  /**
   * @param {!proto.ro.tuc.ds2020.grpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ro.tuc.ds2020.grpc.UserList.deserializeBinary
);


/**
 * @param {!proto.ro.tuc.ds2020.grpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ro.tuc.ds2020.grpc.UserList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ro.tuc.ds2020.grpc.UserList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ro.tuc.ds2020.grpc.ChatServiceClient.prototype.getAllUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ro.tuc.ds2020.grpc.ChatService/getAllUsers',
      request,
      metadata || {},
      methodDescriptor_ChatService_getAllUsers,
      callback);
};


/**
 * @param {!proto.ro.tuc.ds2020.grpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ro.tuc.ds2020.grpc.UserList>}
 *     Promise that resolves to the response
 */
proto.ro.tuc.ds2020.grpc.ChatServicePromiseClient.prototype.getAllUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ro.tuc.ds2020.grpc.ChatService/getAllUsers',
      request,
      metadata || {},
      methodDescriptor_ChatService_getAllUsers);
};


module.exports = proto.ro.tuc.ds2020.grpc;

