// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package ro.tuc.ds2020.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.ds2020.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
