// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package ro.tuc.ds2020.grpc;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.ds2020.grpc.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ro.tuc.ds2020.grpc.User users = 1;</code>
   */
  java.util.List<ro.tuc.ds2020.grpc.User> 
      getUsersList();
  /**
   * <code>repeated .ro.tuc.ds2020.grpc.User users = 1;</code>
   */
  ro.tuc.ds2020.grpc.User getUsers(int index);
  /**
   * <code>repeated .ro.tuc.ds2020.grpc.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .ro.tuc.ds2020.grpc.User users = 1;</code>
   */
  java.util.List<? extends ro.tuc.ds2020.grpc.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .ro.tuc.ds2020.grpc.User users = 1;</code>
   */
  ro.tuc.ds2020.grpc.UserOrBuilder getUsersOrBuilder(
      int index);
}
